print(1 + 5)
print(10 - 9)
print(12 * 2)
print(80 / 4)
print(90 // 4)
print(17 % 3)
print(12 ** 3)
a=str(input('Введите своё имя:'))
b=str(input('Введите свою фамилию:'))
print('Hello')
print(a + b)
print(id(a),id(b))